export default {
  login: "Razaul00003",
  id: 62474138,
  node_id: "MDQ6VXNlcjYyNDc0MTM4",
  avatar_url: "https://avatars.githubusercontent.com/u/62474138?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Razaul00003",
  html_url: "https://github.com/Razaul00003",
  followers_url: "https://api.github.com/users/Razaul00003/followers",
  following_url:
    "https://api.github.com/users/Razaul00003/following{/other_user}",
  gists_url: "https://api.github.com/users/Razaul00003/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Razaul00003/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Razaul00003/subscriptions",
  organizations_url: "https://api.github.com/users/Razaul00003/orgs",
  repos_url: "https://api.github.com/users/Razaul00003/repos",
  events_url: "https://api.github.com/users/Razaul00003/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Razaul00003/received_events",
  type: "User",
  site_admin: false,
  name: "Razaul",
  company: null,
  blog: "",
  location: "Dhaka , Bangladesh",
  email: null,
  hireable: null,
  bio: "Passionate Javascript Developer || React || React Native",
  twitter_username: null,
  public_repos: 29,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-03-21T14:55:50Z",
  updated_at: "2022-10-03T13:13:06Z",
};
